apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicada-web
  template:
    metadata:
      labels:
        app: cicada-web
    spec:
      containers:
      - name: cicada-web
        image: cicada-web:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicada-web
spec:
  type: ClusterIP
  selector:
    app: cicada-web
  ports:
  - port: 80
    targetPort: 3000
